GET http://localhost:5050/api/v1/tasks

###


GET http://localhost:5050/api/v1/tasks/1

###


POST http://localhost:5050/api/v1/tasks
Content-Type: application/json

{
    "parentId" :1,
    "title":"Rest Test",
    "description": "An awesome description",
    "start": 15,
    "end": null
}